##
## This is the repository configuration for the GitHub repo where the
## flux configuration is located.
##
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: bimlens-flux-repository-dev
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/balintbende/bimlens-flux.git