apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: api-dev-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: api-dev-image-repository
  filterTags:
    pattern: '^develop-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
# apiVersion: image.toolkit.fluxcd.io/v1
# kind: ImagePolicy
# metadata:
#   name: web-dev-image-policy
#   namespace: flux-system
# spec:
#   imageRepositoryRef:
#     name: web-dev-image-repository
#   filterTags:
#     pattern: '^develop-[a-f0-9]+-(?P<ts>[0-9]+)'
#     extract: '$ts'
#   policy:
#     numerical:
#       order: asc