# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 24h

grafana:
  enabled: true
