apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.serviceName }}
  labels:
    app.kubernetes.io/name: {{ .Values.web.serviceName }}
    helm.sh/chart: {{ include "bimlens.chart" . }}
    app.kubernetes.io/instance: {{ .Values.web.serviceName }}
    app.kubernetes.io/managed-by: {{ .Values.web.serviceName }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.web.port }}
      targetPort: 8080
      protocol: TCP
      name: "public-web"
  selector:
    app.kubernetes.io/name: {{ .Values.web.serviceName }}
    app.kubernetes.io/instance: {{ .Values.web.serviceName }}
