apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bimlens
spec:
  interval: 1m
  chart:
    spec:
      chart: charts
      sourceRef:
        kind: GitRepository
        name: bimlens-helm-repository-dev
        namespace: flux-system
  rollback:
    timeout: 5m
    disableWait: false
    disableHooks: false
    recreate: false
    force: true
    cleanupOnFail: false
  values:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
    default:
      namespace: "dev"
      nodeGroupProfile: "default"
    api:
      image: ghcr.io/balintbende/bimlens/api:develop-23cddc4-1790071054 # {"$imagepolicy": "flux-system:api-dev-image-policy"}
      replicas: 1
      host: ""
      serviceName: "api"
    web:
      image: ghcr.io/balintbende/bimlens/web:develop-23cddc4-1790071033 # {"$imagepolicy": "flux-system:web-dev-image-policy"}
      replicas: 1
      host: ""
      serviceName: "web"
